local ADDON_NAME, ns = ...
local NephUI = ns.Addon

NephUI.viewers = {
    "EssentialCooldownViewer",
    "UtilityCooldownViewer",
    "BuffIconCooldownViewer",
}

local defaults = {
    profile = {
        general = {
            globalTexture = "Neph",
            globalFont = "Expressway",
            applyGlobalFontToBlizzard = true,
            eyefinity = false,
            ultrawide = false,
            uiScale = nil,
        },
        viewers = {
            general = {
                cooldownFontSize = 18,
                cooldownTextColor = {1, 1, 1, 1},
                cooldownShadowOffsetX = 0,
                cooldownShadowOffsetY = 0,
                procGlow = {
                    enabled = true,
                    glowType = "Pixel Glow",
                    loopColor = {0.95, 0.95, 0.32, 1},
                    lcgLines = 10,
                    lcgFrequency = 0.25,
                    lcgThickness = 1,
                },
            },
            EssentialCooldownViewer = {
                enabled          = true,
                iconSize         = 48,
                aspectRatioCrop  = 1.0,
                spacing          = 1,
                zoom             = 0.08,
                borderSize       = 1,
                borderColor      = { 0, 0, 0, 1 },
                chargeTextAnchor = "BOTTOMRIGHT",
                countTextSize    = 16,
                countTextOffsetX = 0,
                countTextOffsetY = 0,
                rowLimit         = 0,
                rowIconSizes     = {},
                primaryDirection = "CENTERED_HORIZONTAL",
                secondaryDirection = nil,
                cooldownFontSize = 18,
                cooldownTextColor = {1, 1, 1, 1},
                cooldownShadowOffsetX = 0,
                cooldownShadowOffsetY = 0,
            },
            UtilityCooldownViewer = {
                enabled          = true,
                iconSize         = 48,
                aspectRatioCrop  = 1.0,
                spacing          = 1,
                zoom             = 0.08,
                borderSize       = 1,
                borderColor      = { 0, 0, 0, 1 },
                chargeTextAnchor = "BOTTOMRIGHT",
                countTextSize    = 16,
                countTextOffsetX = 0,
                countTextOffsetY = 0,
                rowLimit         = 0,
                rowIconSizes     = {},
                primaryDirection = "CENTERED_HORIZONTAL",
                secondaryDirection = nil,
                cooldownFontSize = 18,
                cooldownTextColor = {1, 1, 1, 1},
                cooldownShadowOffsetX = 0,
                cooldownShadowOffsetY = 0,
            },
            BuffIconCooldownViewer = {
                enabled          = true,
                iconSize         = 38,
                aspectRatioCrop  = 1.0,
                spacing          = 1,
                zoom             = 0.08,
                borderSize       = 1,
                borderColor      = { 0, 0, 0, 1 },
                chargeTextAnchor = "BOTTOMRIGHT",
                countTextSize    = 14,
                countTextOffsetX = 0,
                countTextOffsetY = 0,
                rowLimit         = 0,
                rowIconSizes     = {},
                primaryDirection = "CENTERED_HORIZONTAL",
                secondaryDirection = nil,
                cooldownFontSize = 18,
                cooldownTextColor = {1, 1, 1, 1},
                cooldownShadowOffsetX = 0,
                cooldownShadowOffsetY = 0,
            },
        },
        buffBarViewer = {
            enabled = true,
            width = 0,           -- 0 = auto width based on anchor
            height = 16,
            hideIconMask = true,
            hideIcon = false,
            borderSize = 1,
            borderColor = { 0, 0, 0, 1 },
            texture = nil,
            barColor = { 0.9, 0.9, 0.9, 1 },
            bgColor = { 0.15, 0.15, 0.15, 1 },
            iconZoom = 0.08,
            iconBorderSize = 1,
            iconBorderColor = { 0, 0, 0, 1 },
            showName = true,
            nameSize = 14,
            nameColor = { 1, 1, 1, 1 },
            nameAnchor = "LEFT",
            nameOffsetX = 0,
            nameOffsetY = 0,
            showDuration = true,
            durationSize = 12,
            durationColor = { 1, 1, 1, 1 },
            durationAnchor = "RIGHT",
            durationOffsetX = 0,
            durationOffsetY = 0,
            showApplications = true,
            applicationsSize = 12,
            applicationsColor = { 1, 1, 1, 1 },
            applicationsAnchor = "BOTTOMRIGHT",
            applicationsOffsetX = 0,
            applicationsOffsetY = 0,
            barSpacing = 2,
            barColors = {},
            barColorsBySpec = {},
        },
        powerBar = {
            enabled           = true,
            attachTo          = "EssentialCooldownViewer",
            anchorPoint       = "TOP",
            height            = 14,
            offsetY           = 10,
            width             = 0,
            texture           = nil,  
            useClassColor     = true,
            showManaAsPercent = true,
            showText          = true,
            showTicks         = true, 
            textSize          = 20,
            textX             = 1,
            textY             = 2,
            bgColor           = { 0.15, 0.15, 0.15, 1 },
        },
        secondaryPowerBar = {
            enabled       = true,
            attachTo      = "EssentialCooldownViewer",
            anchorPoint   = "TOP",
            height        = 14,
            offsetY       = 27,
            width         = 0,
            texture       = nil,
            useClassColor = false,
            showManaAsPercent = true,
            hideWhenMana  = false,
            showText      = true,
            showTicks     = true,
            hideBarShowText = false,
            showFragmentedPowerBarText  = false,
            textSize      = 16,
            textX         = 1,
            textY         = 2,
            runeTimerTextSize = 10,
            runeTimerTextX    = 0,
            runeTimerTextY    = 0,
            chargedColor  = { 0.22, 0.62, 1.0, 0.8 },
            bgColor       = { 0.15, 0.15, 0.15, 1 },
        },
        powerTypeColors = {
            useClassColor = true,
            colors = {
                -- Primary Power Types
                [Enum.PowerType.Mana] = { 0.00, 0.00, 1.00, 1.0 },
                [Enum.PowerType.Rage] = { 1.00, 0.00, 0.00, 1.0 },
                [Enum.PowerType.Focus] = { 1.00, 0.50, 0.25, 1.0 },
                [Enum.PowerType.Energy] = { 1.00, 1.00, 0.00, 1.0 },
                [Enum.PowerType.RunicPower] = { 0.00, 0.82, 1.00, 1.0 },
                [Enum.PowerType.LunarPower] = { 0.30, 0.52, 0.90, 1.0 },
                [Enum.PowerType.Fury] = { 0.79, 0.26, 0.99, 1.0 },
                [Enum.PowerType.Maelstrom] = { 0.00, 0.50, 1.00, 1.0 },
                -- Secondary Power Types
                [Enum.PowerType.Runes] = { 0.77, 0.12, 0.23, 1.0 },
                ["SOUL"] = { 0.64, 0.19, 0.79, 1.0 },
                [Enum.PowerType.ComboPoints] = { 1.00, 0.96, 0.41, 1.0 },
                [Enum.PowerType.Essence] = { 0.20, 0.58, 0.50, 1.0 },
                [Enum.PowerType.ArcaneCharges] = { 0.20, 0.60, 1.00, 1.0 },
                ["STAGGER"] = { 1.00, 0.42, 0.42, 1.0 }, -- Default to red, dynamic in code
                [Enum.PowerType.Chi] = { 0.00, 1.00, 0.59, 1.0 },
                [Enum.PowerType.HolyPower] = { 0.95, 0.90, 0.60, 1.0 },
                [Enum.PowerType.SoulShards] = { 0.58, 0.51, 0.79, 1.0 },
                ["MAELSTROM_WEAPON"] = { 0.00, 0.50, 1.00, 1.0 },
            },
        },
        castBar = {
            enabled       = true,
            attachTo      = "EssentialCooldownViewer",
            height        = 24,
            offsetY       = -83,
            showIcon      = true,
            texture       = nil,  
            color         = { 1.0, 0.7, 0.0, 1.0 },
            useClassColor = false,
            textSize      = 16,
            width         = 0,
            bgColor       = { 0.1, 0.1, 0.1, 1 },
            showTimeText  = true,
        },
        targetCastBar = {
            enabled       = true,
            attachTo      = "NephUI_Target",
            height        = 24,
            offsetY       = -38,
            showIcon      = true,
            texture       = nil,  
            color         = { 1.0, 0.0, 0.0, 1.0 },
            interruptibleColor    = { 0.3, 0.7, 1.0, 1.0 },
            nonInterruptibleColor = { 0.6, 0.6, 0.6, 1.0 },
            interruptedColor      = { 0.9, 0.2, 0.2, 1.0 },
            textSize      = 16,
            width         = 0,
            bgColor       = { 0.1, 0.1, 0.1, 1 },
            showTimeText  = true,
        },
        focusCastBar = {
            enabled       = true,
            attachTo      = "NephUI_Focus",
            height        = 24,
            offsetY       = 30,
            showIcon      = true,
            texture       = nil,
            color         = { 1.0, 0.0, 0.0, 1.0 },
            interruptibleColor    = { 1.0, 0.0, 0.0, 1.0 },
            nonInterruptibleColor = { 0.6, 0.6, 0.6, 1.0 },
            interruptedColor      = { 0.8, 0.2, 0.2, 1.0 },
            textSize      = 16,
            width         = 0,
            bgColor       = { 0.1, 0.1, 0.1, 1 },
            showTimeText  = true,
        },
        bossCastBar = {
            enabled       = true,
            height        = 24,
            offsetX       = 0,
            offsetY       = -26.00,
            anchorPoint   = "BOTTOM",
            showIcon      = true,
            texture       = nil,
            color         = { 1.0, 0.0, 0.0, 1.0 },
            interruptibleColor    = { 0.3, 0.7, 1.0, 1.0 },
            nonInterruptibleColor = { 0.6, 0.6, 0.6, 1.0 },
            interruptedColor      = { 0.9, 0.2, 0.2, 1.0 },
            textSize      = 16,
            width         = 0,
            bgColor       = { 0.1, 0.1, 0.1, 1 },
            showTimeText  = true,
        },
        partyFrames = {
            enabled = true,
            general = {
                showWhenSolo = false,
                hideHeaderText = true,
                fadeOutOfRange = true,
                outOfRangeAlpha = 0.55,
                hideRangeWidget = false,
                hidePlayerFrame = false,
            },
            layout = {
                useCustomSize = true,
                width = 230,
                height = 46,
                opacity = 1.0,
                spacing = {
                    vertical = 3,
                },
                border = {
                    size = 1,
                    color = {0, 0, 0, 1},
                },
                background = {
                    color = {0.1, 0.1, 0.1, 0.35},
                    classColorAlpha = 0.85,
                    useClassColor = false,
                },
            },
            health = {
                texture = "Neph",
                orientation = "HORIZONTAL",
                useClassColor = true,
                customColor = {0, 0.9, 0, 1},
                background = {
                    color = {0.1, 0.1, 0.1, 1},
                    classColorAlpha = 0.8,
                    useClassColor = false,
                },
            },
            text = {
                health = {
                    enabled = true,
                    format = "PERCENT",
                    abbreviate = false,
                    font = "Expressway",
                    size = 14,
                    outline = "OUTLINE",
                    anchor = "TOPRIGHT",
                    offsetX = 0,
                    offsetY = 0,
                    shadowOffsetX = 0,
                    shadowOffsetY = 0,
                    color = {1, 1, 1, 1},
                    useClassColor = false,
                    showStatusText = true,
                },
                name = {
                    enabled = true,
                    showRealm = false,
                    maxChars = 0,
                    wrapMode = "TRUNCATE",
                    font = "Expressway",
                    size = 14,
                    outline = "OUTLINE",
                    anchor = "TOPLEFT",
                    offsetX = 0,
                    offsetY = 0,
                    shadowOffsetX = 0,
                    shadowOffsetY = 0,
                    color = {1, 1, 1, 1},
                    useClassColor = false,
                },
            },
            icons = {
                leader = {enabled = false, anchor = "TOPLEFT", offsetX = 0, offsetY = 4, scale = 1.0},
                role = {enabled = false, anchor = "BOTTOMRIGHT", offsetX = 0, offsetY = 0, scale = 1.0},
                raid = {enabled = false, anchor = "TOP", offsetX = 0, offsetY = 2, scale = 1.5},
                ready = {enabled = false, anchor = "CENTER", offsetX = 0, offsetY = 0, scale = 1.0},
                centerStatus = {enabled = false, anchor = "CENTER", offsetX = 0, offsetY = 0, scale = 1.0},
                dispel = {
                    hide = false,
                    anchor = nil,
                    offsetX = 0,
                    offsetY = 0,
                    scale = 1.0,
                },
            },
            auras = {
                buffs = {
                    enabled = false,
                    anchor = "BOTTOMRIGHT",
                    offsetX = 0,
                    offsetY = 0,
                    horizontalGrowth = "LEFT",
                    verticalGrowth = "UP",
                    size = 36,
                    alpha = 1.0,
                    borderSize = 1,
                    spacingX = 3,
                    spacingY = 3,
                    perRow = 0,
                    max = 12,
                    wrapOffsetX = 0,
                    wrapOffsetY = 0,
                    clickThrough = false,
                    stack = {font = "Expressway", size = 12, outline = "OUTLINE", anchor = "BOTTOMRIGHT", offsetX = 0, offsetY = 0},
                    countdown = {enabled = false, font = "Expressway", size = 12, outline = "OUTLINE", offsetX = 0, offsetY = 0},
                    hideSwipe = false,
                },
                debuffs = {
                    enabled = true,
                    anchor = "BOTTOMLEFT",
                    offsetX = 0,
                    offsetY = 0,
                    horizontalGrowth = "RIGHT",
                    verticalGrowth = "UP",
                    size = 36,
                    alpha = 1.0,
                    borderSize = 0,
                    spacingX = 3,
                    spacingY = 3,
                    perRow = 0,
                    max = 12,
                    wrapOffsetX = 0,
                    wrapOffsetY = 0,
                    clickThrough = false,
                    stack = {font = "Expressway", size = 12, outline = "OUTLINE", anchor = "BOTTOMRIGHT", offsetX = 0, offsetY = 0},
                    countdown = {enabled = false, font = "Expressway", size = 12, outline = "OUTLINE", offsetX = 0, offsetY = 0},
                    hideSwipe = false,
                },
                centerDefensive = {
                    size = 22,
                    anchor = "CENTER",
                    offsetX = 0,
                    offsetY = 0,
                    borderSize = 1,
                },
            },
            resource = {
                enabled = true,
                healerOnly = true,
                matchHealthWidth = true,
                width = 50,
                height = 2,
                anchor = "BOTTOM",
                offsetX = 0,
                offsetY = 0,
                orientation = "HORIZONTAL",
                reverseFill = false,
                texture = "Neph",
                color = {0.2, 0.6, 1, 1},
                useClassColor = true,
                usePowerColor = false,
                backgroundColor = {0, 0, 0, 0.5},
            },
            healAbsorbs = {
                enabled = true,
                mode = "OVERLAY",
                width = 60,
                height = 6,
                anchor = "BOTTOM",
                offsetX = 0,
                offsetY = 0,
                orientation = "HORIZONTAL",
                reverseFill = false,
                texture = "Neph",
                color = {0.4, 0.1, 0.1, 0.7},
                anchorPoint = "RIGHT",
                background = {0, 0, 0, 0.4},
            },
            damageAbsorbs = {
                enabled = true,
                texture = "Neph",
                color = {0.15, 0.35, 0.8, 0.7},
                anchorPoint = "RIGHT",
                hideBlizzardGlow = false,
            },
            highlights = {
                selection = {mode = "BLIZZARD", thickness = 2, inset = 0, color = {1, 1, 1, 1}, alpha = 0.4},
                aggro = {mode = "BLIZZARD", thickness = 2, inset = 0, alpha = 1.0},
                blizzardSelection = {enabled = true},
                blizzardAggro = {enabled = true},
                mouseover = {enabled = true, alpha = 0.5},
            },
        },
        raidFrames = {
            enabled = true,
            general = {
                hideGroupLabels = false,
                fadeOutOfRange = true,
                outOfRangeAlpha = 0.55,
                hideRangeWidget = false,
            },
            layout = {
                useCustomSize = false,
                width = 100,
                height = 58,
                opacity = 1.0,
                spacing = {
                    vertical = 3,
                },
                border = {
                    size = 1,
                    color = {0, 0, 0, 0.85},
                },
                background = {
                    color = {0.1, 0.1, 0.1, 0.35},
                    classColorAlpha = 1,
                    useClassColor = false,
                },
            },
            health = {
                texture = "Neph",
                orientation = "HORIZONTAL",
                useClassColor = true,
                customColor = {0, 0.9, 0, 1},
                background = {
                    color = {0.1, 0.1, 0.1, 1},
                    classColorAlpha = 0.8,
                    useClassColor = false,
                },
            },
            text = {
                health = {
                    enabled = false,
                    format = "PERCENT",
                    abbreviate = false,
                    font = "Expressway",
                    size = 12,
                    outline = "OUTLINE",
                    anchor = "CENTER",
                    offsetX = 0,
                    offsetY = 0,
                    shadowOffsetX = 0,
                    shadowOffsetY = 0,
                    color = {1, 1, 1, 1},
                    useClassColor = false,
                    showStatusText = true,
                },
                name = {
                    enabled = true,
                    showRealm = false,
                    maxChars = 14,
                    wrapMode = "TRUNCATE",
                    font = "Expressway",
                    size = 11,
                    outline = "OUTLINE",
                    anchor = "TOPLEFT",
                    offsetX = 1,
                    offsetY = -1,
                    shadowOffsetX = 0,
                    shadowOffsetY = 0,
                    color = {1, 1, 1, 1},
                    useClassColor = false,
                },
            },
            icons = {
                leader = {enabled = false, anchor = "TOPLEFT", offsetX = 0, offsetY = 4, scale = 1.0},
                role = {enabled = false, anchor = "BOTTOMRIGHT", offsetX = 0, offsetY = 0, scale = 1.0},
                raid = {enabled = false, anchor = "TOP", offsetX = 0, offsetY = 2, scale = 1.5},
                ready = {enabled = false, anchor = "CENTER", offsetX = 0, offsetY = 0, scale = 1.0},
                centerStatus = {enabled = false, anchor = "CENTER", offsetX = 0, offsetY = 0, scale = 1.0},
                dispel = {
                    hide = false,
                    anchor = nil,
                    offsetX = 0,
                    offsetY = 0,
                    scale = 1.0,
                },
            },
            auras = {
                buffs = {
                    enabled = true,
                    anchor = "BOTTOMRIGHT",
                    offsetX = 0,
                    offsetY = 0,
                    horizontalGrowth = "LEFT",
                    verticalGrowth = "UP",
                    size = 36,
                    alpha = 1.0,
                    borderSize = 1,
                    spacingX = 3,
                    spacingY = 3,
                    perRow = 3,
                    max = 3,
                    wrapOffsetX = 0,
                    wrapOffsetY = 0,
                    clickThrough = false,
                    stack = {font = "Expressway", size = 11, outline = "OUTLINE", anchor = "BOTTOMRIGHT", offsetX = 0, offsetY = 0},
                    countdown = {enabled = false, font = "Expressway", size = 11, outline = "OUTLINE", offsetX = 0, offsetY = 0},
                    hideSwipe = false,
                },
                debuffs = {
                    enabled = true,
                    anchor = "BOTTOMLEFT",
                    offsetX = 0,
                    offsetY = 0,
                    horizontalGrowth = "RIGHT",
                    verticalGrowth = "UP",
                    size = 36,
                    alpha = 1.0,
                    borderSize = 0,
                    spacingX = 3,
                    spacingY = 3,
                    perRow = 0,
                    max = 12,
                    wrapOffsetX = 0,
                    wrapOffsetY = 0,
                    clickThrough = false,
                    stack = {font = "Expressway", size = 11, outline = "OUTLINE", anchor = "BOTTOMRIGHT", offsetX = 0, offsetY = 0},
                    countdown = {enabled = false, font = "Expressway", size = 11, outline = "OUTLINE", offsetX = 0, offsetY = 0},
                    hideSwipe = false,
                },
                centerDefensive = {
                    size = 20,
                    anchor = "CENTER",
                    offsetX = 0,
                    offsetY = 0,
                    borderSize = 1,
                },
            },
            resource = {
                enabled = true,
                healerOnly = true,
                matchHealthWidth = true,
                width = 50,
                height = 3,
                anchor = "BOTTOM",
                offsetX = 0,
                offsetY = 0,
                orientation = "HORIZONTAL",
                reverseFill = false,
                texture = "Neph",
                color = {0.2, 0.6, 1, 1},
                useClassColor = true,
                usePowerColor = false,
                backgroundColor = {0, 0, 0, 1},
            },
            healAbsorbs = {
                enabled = true,
                mode = "OVERLAY",
                width = 60,
                height = 5,
                anchor = "BOTTOM",
                offsetX = 0,
                offsetY = 0,
                orientation = "HORIZONTAL",
                reverseFill = false,
                texture = "Neph",
                color = {0.4, 0.1, 0.1, 0.7},
                anchorPoint = "RIGHT",
                background = {0, 0, 0, 0.4},
            },
            damageAbsorbs = {
                enabled = true,
                texture = "Neph",
                color = {0.15, 0.35, 0.8, 0.7},
                anchorPoint = "RIGHT",
                hideBlizzardGlow = false,
            },
            highlights = {
                selection = {mode = "BLIZZARD", thickness = 2, inset = 0, color = {1, 1, 1, 1}, alpha = 0.4},
                aggro = {mode = "BLIZZARD", thickness = 2, inset = 0, alpha = 1.0},
                blizzardSelection = {enabled = true},
                blizzardAggro = {enabled = true},
                mouseover = {enabled = true, alpha = 0.5},
            },
        },
        customIcons = {
            enabled = true,
            countTextSize = 16,
            countTextX = -2,
            countTextY = 2,
            countTextAnchor = "BOTTOMRIGHT",
            trackedItems = {},
            consumables = {
                iconSize = 44,
                aspectRatioCrop = 1.0,
                spacing = 1,
                rowLimit = 0,
                growthDirection = "Right",
                anchorPoint = "BOTTOMLEFT",
                borderSize = 1,
                borderColor = { 0, 0, 0, 1 },
                anchorFrame = "NephUI_Player",
                offsetX = 1,
                offsetY = -2,
                hideUnusableItems = false,
                countTextSize = 16,
                countTextX = -2,
                countTextY = 2,
                countTextAnchor = "BOTTOMRIGHT",
                item_241304 = true,
                item_241300 = true,
                item_241308 = true,
                item_241288 = true,
                item_241292 = true,
                item_241296 = true,
                item_241294 = true,
                item_241286 = true,
                item_241302 = true,
            },
            -- Legacy settings (kept for backward compatibility)
            items = {
                iconSize = 44,
                aspectRatioCrop = 1.0,
                spacing = 1,
                rowLimit = 0,
                growthDirection = "Right",
                anchorPoint = "BOTTOMLEFT",
                borderSize = 1,
                borderColor = { 0, 0, 0, 1 },
                anchorFrame = "NephUI_Player",
                offsetX = 1,
                offsetY = -2,
                hideUnusableItems = false,
            },
            trinkets = {
                trinket1 = true,
                trinket2 = true,
                weapon1 = true,
                weapon2 = true,
                iconSize = 44,
                aspectRatioCrop = 1.0,
                spacing = 1,
                rowLimit = 0,
                growthDirection = "LEFT",
                anchorPoint = "TOPRIGHT",
                borderSize = 1,
                borderColor = { 0, 0, 0, 1 },
                anchorFrame = "NephUI_Player",
                offsetX = -1,
                offsetY = 49,
                hideUnusableItems = true,
                countTextSize = 16,
                countTextX = -2,
                countTextY = 2,
                countTextAnchor = "BOTTOMRIGHT",
            },
            defensives = {
                -- Default defensive spells (will be populated based on class)
                enabled = true,
                iconSize = 44,
                aspectRatioCrop = 1.0,
                spacing = 1,
                rowLimit = 0,
                growthDirection = "LEFT",
                anchorPoint = "TOPRIGHT",
                borderSize = 1,
                borderColor = { 0, 0, 0, 1 },
                anchorFrame = "NephUI_Player",
                offsetX = -1,
                offsetY = 2,
                hideUnusableSpells = true,
                countTextSize = 16,
                countTextX = -2,
                countTextY = 2,
                countTextAnchor = "BOTTOMRIGHT",
            },
            racials = {
                iconSize = 44,
                aspectRatioCrop = 1.0,
                spacing = 1,
                rowLimit = 0,
                growthDirection = "LEFT",
                anchorPoint = "TOPRIGHT",
                borderSize = 1,
                borderColor = { 0, 0, 0, 1 },
                anchorFrame = "NephUI_Player",
                offsetX = 0,
                offsetY = -45,
                hideUnusableSpells = true,
                spell_274738 = true,
                spell_202719 = true,
                spell_26297 = true,
                spell_20572 = true,
                spell_255654 = true,
                spell_20577 = true,
                spell_68992 = true,
                spell_20589 = true,
                spell_265221 = true,
                spell_28880 = true,
                spell_287712 = true,
                spell_312924 = true,
                spell_255647 = true,
                spell_107079 = true,
                spell_69070 = true,
                spell_58984 = true,
                spell_256948 = true,
                spell_20594 = true,
                spell_20549 = true,
                spell_7744 = true,
                spell_59752 = true,
                spell_357214 = true,
            },
        },
        dynamicIcons = {
            enabled = true,
            iconData = {},
            ungrouped = {},
            groups = {},
        },
        unitFrames = {
            enabled = true,
            General = {
                ShowEditModeAnchors = false,
                Font = "Expressway",
                FontFlag = "OUTLINE",
                FontShadows = {
                    Color = {0, 0, 0, 0},
                    OffsetX = 0,
                    OffsetY = 0
                },
                ForegroundTexture = nil,  
                BackgroundTexture = nil,  
                CustomColors = {
                    Reaction = {
                        [1] = {204/255, 64/255, 64/255},
                        [2] = {204/255, 64/255, 64/255},
                        [3] = {204/255, 128/255, 64/255},
                        [4] = {255/255, 234/255, 126/255},
                        [5] = {64/255, 204/255, 64/255},
                        [6] = {64/255, 204/255, 64/255},
                        [7] = {64/255, 204/255, 64/255},
                        [8] = {64/255, 204/255, 64/255},
                    },
                    Power = {
                        [0] = {0, 0.50, 1},
                        [1] = {1, 0, 0},
                        [2] = {1, 0.5, 0.25},
                        [3] = {1, 1, 0},
                        [6] = {0, 0.82, 1},
                        [8] = {0.3, 0.52, 0.9},
                        [11] = {0, 0.5, 1},
                        [13] = {0.4, 0, 0.8},
                        [17] = {0.79, 0.26, 0.99},
                        [18] = {1, 0.61, 0}
                    },
                },
                MouseoverHighlight = {
                    Enabled = true,
                    Alpha = 0.5,
                },
            },
            player = {
                Enabled = true,
                Frame = {
                    Width = 269,
                    Height = 48,
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    AnchorFrame = "EssentialCooldownViewer",
                    AnchorToCooldown = true,
                    OffsetX = 0,
                    OffsetY = 0,
                    ClassColor = true,
                    ReactionColor = false,
                    FGColor = {26/255, 26/255, 26/255, 1.0},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                PowerBar = {
                    Enabled = true,
                    Height = 2,
                    ColorByType = true,
                    ColorBackgroundByType = false,
                    FGColor = {8/255, 8/255, 8/255, 0.8},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                AbsorbBar = {
                    Texture = "Neph",
                    FillDirection = "left",
                    AnchorMode = "health",
                    Color = {0.3, 0.5, 0.8, 0.8},
                },
                Tags = {
                    Name = {
                        Enabled = true,
                        AnchorFrom = "LEFT",
                        AnchorTo = "LEFT",
                        OffsetX = 3,
                        OffsetY = 0,
                        FontSize = 14,
                        Color = {1, 1, 1, 1},
                        ColorByStatus = false,
                        MaxLength = 0,
                    },
                    Health = {
                        Enabled = true,
                        AnchorFrom = "RIGHT",
                        AnchorTo = "RIGHT",
                        OffsetX = -3,
                        OffsetY = 0,
                        FontSize = 14,
                        Color = {1, 1, 1, 1},
                        DisplayPercent = true,
                    },
                    Power = {
                        Enabled = false,
                        AnchorFrom = "BOTTOMRIGHT",
                        AnchorTo = "BOTTOMRIGHT",
                        OffsetX = -3,
                        OffsetY = 3,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayStyle = "current",
                    },
                },
                StatusIndicators = {
                    Combat = {
                        Enabled = true,
                        Size = 24,
                        AnchorFrom = "CENTER",
                        AnchorTo = "CENTER",
                        OffsetX = 3,
                        OffsetY = -3,
                        Texture = "DEFAULT",
                    },
                    Resting = {
                        Enabled = true,
                        Size = 24,
                        AnchorFrom = "CENTER",
                        AnchorTo = "TOPLEFT",
                        OffsetX = 3,
                        OffsetY = -3,
                        Texture = "DEFAULT",
                    },
                },
                Auras = {
                    Debuffs = {
                        Enabled = true,
                        Alpha = 1,
                        OffsetX = 0,
                        OffsetY = 1,
                        Spacing = 1,
                        IconsPerRow = 2,
                        IconSize = 44,
                        AnchorPoint = "TOPLEFT",
                        GrowthDirection = "RIGHT",
                        RowGrowthDirection = "UP",
                    },
                    Buffs = {
                        Enabled = false,
                        Alpha = 1,
                        OffsetX = 0,
                        OffsetY = 45,
                        Spacing = 1,
                        IconsPerRow = 6,
                        IconSize = 44,
                        AnchorPoint = "TOPRIGHT",
                        GrowthDirection = "LEFT",
                        RowGrowthDirection = "UP",
                    },
                },
                LeaderIndicator = {
                    Enabled = true,
                    Size = 15,
                    AnchorFrom = "TOPLEFT",
                    AnchorTo = "TOPLEFT",
                    OffsetX = 0,
                    OffsetY = 2,
                },
            },
            target = {
                Enabled = true,
                Frame = {
                    Width = 269,
                    Height = 48,
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    AnchorFrame = "EssentialCooldownViewer",
                    AnchorToCooldown = true,
                    OffsetX = 0,
                    OffsetY = 0,
                    ClassColor = true,
                    ReactionColor = true,
                    FGColor = {26/255, 26/255, 26/255, 1.0},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                PowerBar = {
                    Enabled = true,
                    Height = 2,
                    ColorByType = true,
                    ColorBackgroundByType = false,
                    FGColor = {8/255, 8/255, 8/255, 0.8},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                AbsorbBar = {
                    Texture = "Neph",
                    FillDirection = "left",
                    AnchorMode = "health",
                    Color = {0.3, 0.5, 0.8, 0.8},
                },
                Tags = {
                    Name = {
                        Enabled = true,
                        AnchorFrom = "LEFT",
                        AnchorTo = "LEFT",
                        OffsetX = 3,
                        OffsetY = 15,
                        FontSize = 14,
                        Color = {1, 1, 1, 1},
                        ColorByStatus = false,
                        MaxLength = 0,
                        InlineTargetTarget = true,
                        TargetTargetSeparator = " » ",
                    },
                    Health = {
                        Enabled = true,
                        AnchorFrom = "LEFT",
                        AnchorTo = "LEFT",
                        OffsetX = 3,
                        OffsetY = -10,
                        FontSize = 14,
                        Color = {1, 1, 1, 1},
                        DisplayPercent = true,
                    },
                    Power = {
                        Enabled = true,
                        AnchorFrom = "BOTTOMRIGHT",
                        AnchorTo = "BOTTOMRIGHT",
                        OffsetX = -3,
                        OffsetY = 3,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayStyle = "current",
                    },
                },
                Auras = {
                    Debuffs = {
                        Enabled = true,
                        Preview = false,
                        Alpha = 1,
                        OffsetX = 0,
                        OffsetY = 1,
                        Spacing = 1,
                        IconsPerRow = 3,
                        IconSize = 44,
                        AnchorPoint = "TOPLEFT",
                        GrowthDirection = "RIGHT",
                        RowGrowthDirection = "UP",
                    },
                    Buffs = {
                        Enabled = true,
                        Preview = false,
                        Alpha = 1,
                        OffsetX = 0,
                        OffsetY = 1,
                        Spacing = 1,
                        IconsPerRow = 3,
                        IconSize = 44,
                        AnchorPoint = "TOPRIGHT",
                        GrowthDirection = "LEFT",
                        RowGrowthDirection = "UP",
                    },
                },
            },
            targettarget = {
                Enabled = true,
                Frame = {
                    Width = 122,
                    Height = 21,
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    AnchorFrame = "NephUI_Target",
                    OffsetX = 196,
                    OffsetY = -14,
                    ClassColor = true,
                    ReactionColor = true,
                    FGColor = {26/255, 26/255, 26/255, 1.0},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                Tags = {
                    Name = {
                        Enabled = true,
                        AnchorFrom = "CENTER",
                        AnchorTo = "CENTER",
                        OffsetX = 0,
                        OffsetY = 0,
                        FontSize = 14,
                        Color = {1, 1, 1, 1},
                        ColorByStatus = false,
                        MaxLength = 0,
                    },
                    Health = {
                        Enabled = false,
                        AnchorFrom = "RIGHT",
                        AnchorTo = "RIGHT",
                        OffsetX = -3,
                        OffsetY = 0,
                        FontSize = 14,
                        Color = {1, 1, 1, 1},
                        DisplayPercent = true,
                    },
                },
                Auras = {
                    Debuffs = {
                        Enabled = true,
                        Preview = false,
                        Alpha = 1,
                        OffsetX = 0,
                        OffsetY = 45,
                        Spacing = 1,
                        IconsPerRow = 6,
                        IconSize = 44,
                        AnchorPoint = "TOPRIGHT",
                        GrowthDirection = "LEFT",
                        RowGrowthDirection = "UP",
                    },
                    Buffs = {
                        Enabled = true,
                        Preview = false,
                        Alpha = 1,
                        OffsetX = 0,
                        OffsetY = 45,
                        Spacing = 1,
                        IconsPerRow = 3,
                        IconSize = 44,
                        AnchorPoint = "TOPLEFT",
                        GrowthDirection = "RIGHT",
                        RowGrowthDirection = "UP",
                    },
                },
            },
            pet = {
                Enabled = true,
                Frame = {
                    Width = 269,
                    Height = 21,
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    AnchorFrame = "NephUI_Player",
                    OffsetX = 0,
                    OffsetY = -36,
                    ClassColor = true,
                    ReactionColor = false,
                    FGColor = {26/255, 26/255, 26/255, 1.0},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                Tags = {
                    Name = {
                        Enabled = true,
                        AnchorFrom = "CENTER",
                        AnchorTo = "CENTER",
                        OffsetX = 0,
                        OffsetY = 0,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        ColorByStatus = false,
                    MaxLength = 0,
                    },
                    Health = {
                        Enabled = false,
                        AnchorFrom = "RIGHT",
                        AnchorTo = "RIGHT",
                        OffsetX = -3,
                        OffsetY = 0,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayPercent = true,
                    },
                    Power = {
                        Enabled = false,
                        AnchorFrom = "BOTTOMRIGHT",
                        AnchorTo = "BOTTOMRIGHT",
                        OffsetX = -3,
                        OffsetY = 3,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayStyle = "both",
                    },
                },
            },
            focus = {
                Enabled = true,
                Frame = {
                    Width = 269,
                    Height = 32,
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    AnchorFrame = "NephUI_Player",
                    OffsetX = 0,
                    OffsetY = 135,
                    ClassColor = true,
                    ReactionColor = true,
                    FGColor = {26/255, 26/255, 26/255, 1.0},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                PowerBar = {
                    Enabled = true,
                    Height = 2,
                    ColorByType = true,
                    ColorBackgroundByType = true,
                    FGColor = {8/255, 8/255, 8/255, 0.8},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                Tags = {
                    Name = {
                        Enabled = true,
                        AnchorFrom = "LEFT",
                        AnchorTo = "LEFT",
                        OffsetX = 3,
                        OffsetY = 0,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        ColorByStatus = false,
                        MaxLength = 0,
                    },
                    Health = {
                        Enabled = true,
                        AnchorFrom = "RIGHT",
                        AnchorTo = "RIGHT",
                        OffsetX = -3,
                        OffsetY = 0,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayPercent = true,
                    },
                    Power = {
                        Enabled = false,
                        AnchorFrom = "BOTTOMRIGHT",
                        AnchorTo = "BOTTOMRIGHT",
                        OffsetX = -3,
                        OffsetY = 3,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayStyle = "both",
                    },
                },
                Auras = {
                    Debuffs = {
                        Enabled = true,
                        Preview = false,
                        Alpha = 1,
                        OffsetX = 0,
                        OffsetY = 1,
                        Spacing = 1,
                        IconsPerRow = 3,
                        IconSize = 44,
                        AnchorPoint = "TOPRIGHT",
                        GrowthDirection = "LEFT",
                        RowGrowthDirection = "UP",
                    },
                    Buffs = {
                        Enabled = true,
                        Preview = false,
                        Alpha = 1,
                        OffsetX = 0,
                        OffsetY = 1,
                        Spacing = 1,
                        IconsPerRow = 3,
                        IconSize = 44,
                        AnchorPoint = "TOPLEFT",
                        GrowthDirection = "RIGHT",
                        RowGrowthDirection = "UP",
                    },
                },
            },
            boss = {
                Enabled = true,
                Frame = {
                    Width = 260,
                    Height = 48,
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    AnchorFrame = "UIParent",
                    OffsetX = 670,
                    OffsetY = -120,
                    ClassColor = true,
                    ReactionColor = true,
                    FGColor = {26/255, 26/255, 26/255, 1.0},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                    GrowthDirection = "UP",
                    Spacing = 28,
                },
                PowerBar = {
                    Enabled = true,
                    Height = 3,
                    ColorByType = true,
                    ColorBackgroundByType = false,
                    FGColor = {8/255, 8/255, 8/255, 0.8},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                AbsorbBar = {
                    Texture = "Neph",
                    FillDirection = "left",
                    AnchorMode = "health",
                    Color = {0.3, 0.5, 0.8, 0.8},
                },
                Tags = {
                    Name = {
                        Enabled = true,
                        AnchorFrom = "LEFT",
                        AnchorTo = "LEFT",
                        OffsetX = 3,
                        OffsetY = 0,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        ColorByStatus = false,
                        MaxLength = 0,
                    },
                    Health = {
                        Enabled = true,
                        AnchorFrom = "RIGHT",
                        AnchorTo = "RIGHT",
                        OffsetX = -3,
                        OffsetY = 0,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayPercent = true,
                    },
                    Power = {
                        Enabled = false,
                        AnchorFrom = "BOTTOMRIGHT",
                        AnchorTo = "BOTTOMRIGHT",
                        OffsetX = -3,
                        OffsetY = 3,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayStyle = "current",
                    },
                },
                CastBar = {
                    Enabled = true,
                    Height = 24,
                    Width = 244,
                    MatchFrameWidth = true,
                    XPosition = 0,
                    YPosition = -1,
                    AnchorFrom = "TOP",
                    AnchorTo = "BOTTOM",
                    FGColour = {128/255, 128/255, 255/255, 1},
                    BGColour = {26/255, 26/255, 26/255, 1},
                    NotInterruptibleColour = {255/255, 64/255, 64/255, 1},
                    Text = {
                        SpellName = {
                            Enabled = true,
                            AnchorFrom = "LEFT",
                            AnchorTo = "LEFT",
                            OffsetX = 3,
                            OffsetY = 0,
                            FontSize = 12,
                            Colour = {1, 1, 1, 1},
                        },
                        Time = {
                            Enabled = true,
                            AnchorFrom = "RIGHT",
                            AnchorTo = "RIGHT",
                            OffsetX = -3,
                            OffsetY = 0,
                            FontSize = 12,
                            Colour = {1, 1, 1, 1},
                        },
                    },
                    Icon = {
                        Enabled = true,
                        Position = "RIGHT",
                    },
                },
                Indicators = {
                    MouseoverHighlight = {
                        Enabled = true,
                        Colour = {1, 1, 1, 1},
                    },
                    RaidTargetMarker = {
                        Enabled = true,
                        Size = 24,
                        AnchorFrom = "CENTER",
                        AnchorTo = "CENTER",
                        OffsetX = 0,
                        OffsetY = 0,
                    },
                    TargetIndicator = {
                        Enabled = true,
                        Colour = {1, 1, 1, 1},
                        Style = "GLOW"
                    }
                },
                Portrait = {
                    Enabled = true,
                    Size = 42,
                    AnchorFrom = "RIGHT",
                    AnchorTo = "LEFT",
                    OffsetX = -1,
                    OffsetY = 0,
                    Zoom = 0.3,
                    MatchFrameHeight = true,
                },
                Auras = {
                    Debuffs = {
                        Enabled = true,
                        Preview = false,
                        Alpha = 1,
                        OffsetX = 0,
                        OffsetY = 1,
                        Spacing = 1,
                        IconsPerRow = 2,
                        IconSize = 32,
                        AnchorPoint = "TOPRIGHT",
                        GrowthDirection = "LEFT",
                        RowGrowthDirection = "UP",
                    },
                    Buffs = {
                        Enabled = false,
                        Preview = false,
                        Alpha = 1,
                        OffsetX = 0,
                        OffsetY = 1,
                        Spacing = 1,
                        IconsPerRow = 2,
                        IconSize = 32,
                        AnchorPoint = "TOPLEFT",
                        GrowthDirection = "RIGHT",
                        RowGrowthDirection = "UP",
                    },
                },
                HealPrediction = {
                    Absorbs = {
                        Enabled = true,
                        Colour = {255/255, 204/255, 0/255, 1},
                        GrowthDirection = "RIGHT",
                    }
                },
                PreviewMode = false,
            },
        },
        chat = {
            enabled = true,
            backgroundColor = { 0.1, 0.1, 0.1, 1 },
            hideQuickJoinToastButton = false,
            quickJoinToastButtonOffsetX = 31,
            quickJoinToastButtonOffsetY = -23,
        },
        minimap = {
            enabled = true,
            size = 230,
            borderSize = 2,
            lock = false,
            position = {"CENTER", "CENTER", 0, 0},
            scale = 1,
            autoZoom = true,
            mouseWheelZoom = true,
            hideBlizzardButtons = true,
            hideZoomButtons = true,
            hideTrackingButton = true,
            hideDifficultyIcon = false,
            difficultyIcon = {
                anchor = "Top Right",
                offsetX = -5,
                offsetY = -5,
            },
            hideMailButton = false,
            mailIcon = {
                anchor = "Top Left",
                offsetX = 3,
                offsetY = -3,
            },
            hideCalendarButton = true,
            hideMissionsButton = true,
            hideAddonCompartment = true,
            zoneText = {
                enabled = true,
                fontSize = 14,
                anchor = "Top",
                offsetX = 0,
                offsetY = -5,
                useCustomColor = false,
                color = {1, 0.82, 0, 1},
                colorNormal = {1, 0.82, 0, 1},
                colorSanctuary = {0.41, 0.8, 0.94, 1},
                colorArena = {1.0, 0.1, 0.1, 1},
                colorFriendly = {0.1, 1.0, 0.1, 1},
                colorHostile = {1.0, 0.1, 0.1, 1},
                colorContested = {1.0, 0.7, 0.0, 1},
            },
            clock = {
                enabled = true,
                fontSize = 16,
                anchor = "Bottom Left",
                color = {1, 1, 1, 1},
                offsetX = 4,
                offsetY = 4,
            },
            fps = {
                enabled = true,
                fontSize = 16,
                anchor = "Bottom Right",
                color = {1, 1, 1, 1},
                updateFrequency = 2,
                offsetX = -4,
                offsetY = 4,
            },
        },
        actionBars = {
            enabled = true,
            backdropColor = {0.1, 0.1, 0.1, 1},
            borderColor = {0, 0, 0, 1},
            borderSize = 1,
            font = nil, -- nil = use global font
            mouseover = {
                enabled = false,
                alpha = 0.0,
                bars = {
                    bar1 = false,
                    bar2 = false,
                    bar3 = false,
                    bar4 = false,
                    bar5 = false,
                    bar6 = false,
                    bar7 = false,
                    bar8 = false,
                    petBar = false,
                    stanceBar = false,
                    microMenu = false,
                },
            },
            keybindText = {
                hide = false,
                fontColor = {0.75, 0.75, 0.75, 1},
                fontSize = 14,
                offsetX = -2,
                offsetY = -4,
            },
            macroText = {
                hide = false,
                fontColor = {1, 1, 1, 1},
                fontSize = 10,
                offsetX = 0,
                offsetY = 2,
            },
            countText = {
                hide = false,
                fontColor = {1, 1, 1, 1},
                fontSize = 16,
                offsetX = -2,
                offsetY = 4,
            },
            procGlow = {
                enabled = true,
                glowType = "Pixel Glow",
                loopColor = {0.95, 0.95, 0.32, 1},
                lcgLines = 14,
                lcgFrequency = 0.25,
                lcgThickness = 1,
            },
        },
        qol = {
            characterPanel = true,
            hideBagsBar = true,
            tooltipIDs = false,
        },
        buffDebuffFrames = {
            enabled = true,
            layout = {
                iconsPerRow = 12,
                iconSpacing = 5,
                rowSpacing = 5,
                anchorSide = "TOPRIGHT",
                growthHorizontal = "LEFT",
                growthVertical = "DOWN",
            },
            buffs = {
                iconSize = 38,
                layout = {
                    iconsPerRow = 12,
                    iconSpacing = 11,
                    rowSpacing = 1,
                    anchorSide = "TOPRIGHT",
                },
                duration = {
                    enabled = true,
                    anchorPoint = "CENTER",
                    offsetX = 0,
                    offsetY = 0,
                    fontSize = 12,
                    fontFlag = "OUTLINE",
                    textColor = {1, 1, 1, 1},
                },
                count = {
                    enabled = true,
                    anchorPoint = "BOTTOMRIGHT",
                    offsetX = 0,
                    offsetY = 0,
                    fontSize = 12,
                    fontFlag = "OUTLINE",
                    textColor = {1, 1, 1, 1},
                },
            },
            debuffs = {
                iconSize = 38,
                layout = {
                    iconsPerRow = 12,
                    iconSpacing = 11,
                    rowSpacing = 1,
                    anchorSide = "TOPRIGHT",
                },
                duration = {
                    enabled = true,
                    anchorPoint = "CENTER",
                    offsetX = 0,
                    offsetY = 0,
                    fontSize = 12,
                    fontFlag = "OUTLINE",
                    textColor = {1, 1, 1, 1},
                },
                count = {
                    enabled = true,
                    anchorPoint = "BOTTOMRIGHT",
                    offsetX = 0,
                    offsetY = 0,
                    fontSize = 12,
                    fontFlag = "OUTLINE",
                    textColor = {1, 1, 1, 1},
                },
            },
        },
    },
}

NephUI.defaults = defaults

